Added views, VMs, models, extensions
deffsin/WeatherAppSwiftUIFS pull request #2
Opened 2023-08-03 21:01 UTC by deffsin

2023-08-14 16:48 UTC, Hassanq911 requested changes

2023-08-14 16:55 UTC, Hassanq911 requested changes

2023-08-14 16:55 UTC, Hassanq911 commented on WeatherAppSwiftUIFS/Models/Store.swift
> +class Store: ObservableObject {
What is the purpose of this Store can this be broken down into usecases ?

2023-08-14 16:55 UTC, Hassanq911 commented on WeatherAppSwiftUIFS/Others/DeleteAllCitiesView.swift
> +    func deleteAllCities() {
This should be done in a viewModel

2023-08-14 16:55 UTC, Hassanq911 commented on WeatherAppSwiftUIFS/ViewModels/WeatherCellViewModel.swift
> +struct WeatherCellViewModel: Identifiable {
You can rename to this WeatherCellDto rather then viewModel because the purpose of this struct is pass data and no business logic is being done here

2023-08-14 21:24 UTC, deffsin commented on WeatherAppSwiftUIFS/API/WeatherAPIHandler.swift
> +class WeatherAPIHandler {
WeatherAPIHandler is something between the UI and the API service, this class transforms the received API data into a ViewModl

2023-08-14 21:26 UTC, Hassanq911 commented on WeatherAppSwiftUIFS/API/WeatherAPIHandler.swift
> +class WeatherAPIHandler {
Alright then following the conventions pls rename this into let’s say `fetchweatherusecase`

2023-08-16 10:44 UTC, Hassanq911 commented on WeatherAppSwiftUIFS/Models/Store.swift
> +class Store: ObservableObject {
??

2023-08-16 10:50 UTC, Hassanq911 requested changes

2023-08-16 10:50 UTC, Hassanq911 commented on WeatherAppSwiftUIFS/Views/AddCityView.swift
> +    @EnvironmentObject var store: Store // viewModel??
Shouldn't this store be in viewModel ?

2023-08-16 10:55 UTC, deffsin commented on WeatherAppSwiftUIFS/Models/Store.swift
> +class Store: ObservableObject {
Aaa, oops, i forgot to reply. This is the main data store. I've already made changes in this commit, using use cases as you suggested

2023-08-18 19:52 UTC, merged